
services:
  # --- Service MySQL ---
  mysql:
    image: mysql:8.0
    container_name: mysql-books
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: bob
      MYSQL_PASSWORD: mdp 
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springnet

  # --- Service Spring Boot (ton app) ---
  app:
    build: .
    container_name: books-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: 
      - mysql
    networks:
      - springnet
volumes:
  mysql_data:

networks:
  springnet: