
services:
  # --- Service MySQL ---
  mysql:
    image: mysql:8.0
    container_name: mysql-books
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: bob
      MYSQL_PASSWORD: mdp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springnet

  # --- Service Spring Boot (ton app) ---
  app:
    build: .
    container_name: books-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booksdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    networks:
      - springnet

volumes:
  mysql_data:

networks:
  springnet: